Home
sara-34/git-practica-1 pull request #3
Opened 2023-02-13 14:59 UTC by sara-34

Uploading page with changes in the home

2023-02-14 04:04 UTC, carlos4rias requested changes

2023-02-14 04:04 UTC, carlos4rias commented on pagina-practica/practica.html
> +    <footer class="contacto" id="contactos">
Why you use a footer here, it is really a footer?, also there is not consistency at the lines 29 and 25 why use article and then section respectively

2023-02-14 04:04 UTC, carlos4rias commented on pagina-practica/practica.html
> +                <div class="informacion">
Why did not use the form element?, always is recommended to use the form element for good practices.

2023-02-14 04:04 UTC, carlos4rias commented on pagina-practica/practica.html
> +                </div>
Always ident the code, there is not very clear which div element are you closing also it is a good practice.

2023-02-14 04:04 UTC, carlos4rias commented on pagina-practica/style.css
> +    margin-top: 10px;
use a single `margin` property, for example
```css
margin: 10px 0 10px 0
```

2023-02-14 04:04 UTC, carlos4rias commented on pagina-practica/style.css
> +    padding-top: 20px;
why using `padding` and `padding-top` properties, mix up in a single `padding` property

2023-02-15 00:51 UTC, sara-34 commented on pagina-practica/practica.html
> +    <footer class="contacto" id="contactos">
making suggestion

2023-02-17 12:50 UTC, carlos4rias requested changes

2023-02-17 12:50 UTC, carlos4rias commented on pagina-practica/style.css
> +#imagen-about{
Why still using ID's as selectors?
https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4  read this please.

2023-02-17 12:50 UTC, carlos4rias commented on pagina-practica/practica.html
> +<div>
Why using a div, you are confused with HTML semantic

2023-02-17 12:50 UTC, carlos4rias commented on pagina-practica/practica.html
> +    <section class="contacto" id="contactos">
Why a section here?

2023-02-17 13:41 UTC, carlos4rias approved these changes

2023-02-17 13:41 UTC, merged